[package]
name = "child"
version = "0.1.0"
edition = "2021"

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
ic-types = "0.4.1"
ic-cdk = { git = "https://github.com/LiveDuo/cdk-rs" }
ic-cdk-macros = { git = "https://github.com/LiveDuo/cdk-rs" }
ic-certified-assets = { git = "https://github.com/LiveDuo/cdk-rs" }
lazy_static = "1.4.0"
serde = "1.0.140"
serde_bytes = "0.11.6"
hex = "0.4.3"
libsecp256k1 = "0.6.0"
easy-hasher = "2.2.1"
candid = "0.7.15"
