[package]
name = "parent"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
path = "lib.rs"
crate-type = ["cdylib"]

[dependencies]
candid = "0.7.4"
ic-cdk = { git = "https://github.com/LiveDuo/cdk-rs" }
ic-cdk-macros = { git = "https://github.com/LiveDuo/cdk-rs" }
ic-ledger-types = { git = "https://github.com/LiveDuo/cdk-rs" }
ic-certified-assets = { git = "https://github.com/LiveDuo/cdk-rs" }
serde = "1.0.126"
serde_bytes = "0.11"
serde_json = "1.0.82"
