
name: Tests

on:
  push:
    branches: [ "master", "debug" ]
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        required: false
        default: false

env:
  RUST_BACKTRACE: short
  CARGO_INCREMENTAL: 0
  CARGO_NET_RETRY: 10
  CI: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Swatinem/rust-cache@v2
      - run: export PATH=~/.cargo/bin:/usr/local/bin/:$PATH
      - run: rustup target add wasm32-unknown-unknown
      - run: wget --output-document install-dfx.sh "https://raw.githubusercontent.com/dfinity/sdk/master/public/install-dfxvm.sh"
      - run: DFX_VERSION=${DFX_VERSION:=0.18.0} DFXVM_INIT_YES=true bash install-dfx.sh
      - run: rm install-dfx.sh
      - run: echo "$HOME/.local/share/dfx/bin" >> $GITHUB_PATH
      - run: source "$HOME/.local/share/dfx/env"
      - run: mkdir -p ~/.config/dfx/ && cp ./test/networks.json ~/.config/dfx/networks.json
      - uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.debug_enabled }}
      - run: dfx --version
      - run: dfx identity whoami
      - run: dfx start --background &> dfx.log
      - run: dfx deploy parent
      - run: npm ci
      - run: npm run test:unit
      - run: npm run upload:parent
      - run: npm run test:parent
      - run: dfx deploy child
      - run: npm run test:child
      - run: npm run test:upgrade
      - run: dfx stop
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          path: dfx.log
